version: '2'
services:
  nginx:
    image: "nginx:alpine"
    ports:
    - 5000:8080
    links:
    - registry:registry
    volumes:
    - ./auth:/etc/nginx/conf.d
    - ./auth/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
  registry:
    image: registry:2
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:5001
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
    ports:
    - 127.0.0.1:5001:5001
    volumes:
    - ./registry:/var/lib/registry
    restart: always
